# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]
  base = "./"
  command = "yarn run build"
  functions = "functions"
  publish = "public"

[dev]
  command = "yarn start"
  targetPort = 8888
  framework = "#custom"

